#!/bin/sh
# postinst script for thermod-monitor-dbstats

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
        adduser --system --home /run/thermod --gecos 'Thermod User,,,' thermod
        mkdir -p /var/lib/thermod
        chown thermod /var/lib/thermod
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        # do nothing
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

# vim: fileencoding=utf-8 tabstop=4 shiftwidth=4 expandtab
